version: "3.7"
services:
  app:
    container_name: phoenixly-app
    build: .
    command:  sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
