version: "3.7"
services:
  postgres:
    container_name: phoenixly-db
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./.var/postgresql:/var/lib/postgresql/data
    ports:
      - "5435:5432"
  app:
    container_name: phoenixly-app
    build: .
    command:  gunicorn --workers=3 --bind=0.0.0.0:8000 config.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
  nginx:
    image: nginx:1.19.8-alpine
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - static_data:/var/www/html/static
      - ./nginx-config:/etc/nginx/nginx-config
volumes:
  static_data: